### ISSUE TITLE
Can't import u3m file

### ISSUE THREAD

**Issue by danpak6** [vizoogmbh/U3M-Blender-Add-on#9]
Hello, 

1. I downloaded the zip file and installed the add-on successfully
2. I tried to import a u3m from file>import, but I can't see the u3m option from the selection
3. I am using Blender 3.3 for Mac M1

Any help would be appreciated.

Thank you!

**Comment by FlorianVizoo3d** [comment]
Hi,
Please check if the add-on is enabled (checkbox next to "Import-Export: Unified 3D Material [U3M] format" is checked) at Edit->Preferences->Add-ons.
The u3m import option will only be shown if the addon is installed AND enabled.

hope it helps!

**Comment by darcyreno** [comment]
Hey @danpak6 Did you ever resolve this? I have the exact same issue on Mac M1 - after successful install, the addon isn't active and not available to enable.

1. I downloaded the zip file and installed the add-on successfully
2. I tried to import a u3m from file>import, but I can't see the u3m option from the selection
3. I am using Blender 3.3 for Mac M1
4. The Unified 3D Material option isn't available to enable in the Addons menu

**Comment by danpak6** [comment]
First, download the zip file and then extract it. Next, place the extracted files into the root folder, and compress the contents into a new zip file. It's important to note that for the Blender plugin to function properly, the Python files must be located in the root folder.

**Comment by CathRo3D** [comment]
Hi - I have the same problem as above. I'm using Mac M3 and can install the addon but it's greyed out with and "undocumented operator" note appearing.

When I go to "show contents", of the blender app folder there are a whole bunch of folders and files and I don't know which is the "root" folder you mention above.  

Also when I tried out highlighting the unzipped filed and folders then "compressing them" again to check if this was the right method, it zips them into an Archive folder - they're still there but in a folder named Archive.

Sorry for being so ignorant of the process but I'm keen to learn and to start using my U3ma files in Blender.  Can you give simplified instructions please?

All help appreciated!

**Comment by FlorianVizoo3d** [comment]
Hi there!

I've looked into your concern, and I'm sorry to hear you're experiencing difficulties. I attempted to replicate the issue on a Mac, but fortunately, everything went smoothly on my end.

So no need to worry about repacking anything – the downloaded file should work perfectly as-is.

To assist you, I've prepared a step-by-step guide to your setup:


1. Download the Addon:

Here's the latest [version](https://github.com/vizoogmbh/U3M-Blender-Add-on/releases/download/1.1.2/import_export_U3M.zip) of the ZIP file you need.
Important on Mac: If you're using Safari, please ensure to uncheck the option "Open safe files after downloading" to prevent automatic unpacking.

2. Installation in Blender:

Launch Blender (preferably version 3.3 or 3.6 LTS). Please note that Blender 4.0 definitely won't work with this addon yet!
Navigate to "Edit" > "Preferences" > "Install an Add-on"
Select the downloaded ZIP file named "import_export_U3M.zip"
Click on the "Install Add-on" button.

3. Activating the Addon:

Now, head to the "Add-ons" tab.
Look for "Import-Export: Unified 3D Material (U3M) format" in the list.
Enable it by checking the corresponding checkbox.

4. Start Importing:

With the addon installed and activated, you're all set -
Simply navigate to "File" > "Import" > "Unified 3D Material (.u3m)" to import your files seamlessly.

You can find some examples of U3M files [here](https://www.u3m.info/). 
Also, please note that U3MA files (the archived version of a U3M file) won't work right out of the box; you'll have to unpack them first, for example using 7zip or a similar tool.

I hope these instructions make the process clearer for you - If you have any further questions or run into any snags along the way, please don't hesitate to reach out!

Best regards, Florian

**Comment by CathRo3D** [comment]
Hi Florian

Thanks for this but unfortunately it's still not working for me.
I have some U3M files that Vizoo recently created for me and I can work
with those in V stitcher, but I'm trying to import trims from Vstitcher to
amend the form in Blender then re-load to Vstitcher.

I have installed the unarchiver app (I didn't realise the "a" indicated
"archive" so that's handy to know thanks), so I can unzip these files too.

I was using Blender 4 so I uninstalled and installed 3.6 LTS.
This let me install the add in, but the option was still greyed out in the
"import files" menu.  This time instead of "undocumented operator", the
blurb beneath the option says "Load U3m File"

I also tried to open a U3m file directly using the Blender app, but this
didn't work either.

I replaced Blender 3.6 with 3.3 and then went through all the same steps -
with the same result.

I have an Intel Mac I was using previously and I tried the same thing on
that machine too (installing Blender 3.6 LTS version) - same result.

I'm stumped?

Cath








Cath Rogan
Principal, Smart Garment People Ltd
+44 (0)345 643 2250
www.smartgarmentpeople.com



All intellectual property rights existing in our designs and products are
and will remain the property of Smart Garment People Ltd.  Any infringement
of these rights will be pursued vigorously.

**Comment by FlorianVizoo3d** [comment]
Hi Cath,

I've been giving some thought to what might be causing the issue you're encountering. It seems like you've successfully installed and enabled the addon, which is a great step forward!

Here's a possibility: the option appearing under "File" > "Import" > "Unified 3D Material (.u3m)" suggests that the addon is recognized by Blender. However, if there's no object present in your Blender scene, the option may remain grayed out.

The reason behind this is that a U3M file contains a material texture but isn't a 3D object or mesh on its own. It needs to be applied or imported onto a 3D object or mesh within Blender to be visible and usable.

So, I recommend adding a mesh to your scene – something simple like a "plane" or "cube" will do the trick. Once you've done that, you should find that you're able to import your U3M files and work with them as textures on your objects.

I hope this helps clarify things a bit! Let me know how it goes or if you have any further questions.

Best regards,
Florian
